# Generated by Django 2.1.3 on 2018-12-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile')], default='mobile', max_length=30),
        ),
    ]
