# Generated by Django 2.1.3 on 2019-01-09 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20181224_0702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='department_uuid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='factory_uuid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='position_uuid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_uuid',
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(blank=True, help_text='Different types of user uuid, like admin_user, worker, super_user', max_length=150, null=True),
        ),
    ]
