# Generated by Django 2.1.3 on 2019-01-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20190109_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(blank=True, help_text='Different types of user uuid like Admin, Worker, Superuser', max_length=150, null=True),
        ),
    ]
