# Generated by Django 2.1.3 on 2019-04-08 06:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default=datetime.datetime(2019, 4, 8, 6, 52, 53, 19143, tzinfo=utc), help_text='Different types of user uuid like Admin, Worker, Superuser', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
