# Generated by Django 2.1.3 on 2019-03-05 05:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySubscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4)),
                ('package_uuid', models.CharField(blank=True, help_text='UUID from organization package table', max_length=150, null=True)),
                ('company_uuid', models.CharField(blank=True, help_text='UUID from company table', max_length=150, null=True)),
                ('on_boarding_date', models.DateTimeField(auto_now_add=True)),
                ('expire_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'company_subscription',
                'verbose_name_plural': 'company_subscriptions',
            },
        ),
        migrations.CreateModel(
            name='ConnectModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EngageModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HrModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='companysubscriptions',
            name='connect',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='connect_module_subscription', to='authorization.ConnectModule'),
        ),
        migrations.AddField(
            model_name='companysubscriptions',
            name='engage',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='engage_module_subscription', to='authorization.EngageModule'),
        ),
        migrations.AddField(
            model_name='companysubscriptions',
            name='hr',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hr_module_subscription', to='authorization.HrModule'),
        ),
        migrations.AddField(
            model_name='companysubscriptions',
            name='training',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='training_module_subscription', to='authorization.TrainingModule'),
        ),
    ]
