# Generated by Django 2.1.3 on 2019-03-07 09:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4)),
                ('administrator_uuid', models.CharField(blank=True, help_text='UUID for organization administrator', max_length=150, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='companysubscriptions',
            name='connect',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='company_connect_module_subscription', to='authorization.ConnectModule'),
        ),
        migrations.AlterField(
            model_name='companysubscriptions',
            name='engage',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='company_engage_module_subscription', to='authorization.EngageModule'),
        ),
        migrations.AlterField(
            model_name='companysubscriptions',
            name='hr',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='company_hr_module_subscription', to='authorization.HrModule'),
        ),
        migrations.AlterField(
            model_name='companysubscriptions',
            name='training',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='company_training_module_subscription', to='authorization.TrainingModule'),
        ),
        migrations.AlterField(
            model_name='connectmodule',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engagemodule',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrmodule',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingmodule',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubscriptions',
            name='company_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_company_subscription', to='authorization.CompanySubscriptions'),
        ),
        migrations.AddField(
            model_name='usersubscriptions',
            name='connect',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_connect_module_subscription', to='authorization.ConnectModule'),
        ),
        migrations.AddField(
            model_name='usersubscriptions',
            name='engage',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_engage_module_subscription', to='authorization.EngageModule'),
        ),
        migrations.AddField(
            model_name='usersubscriptions',
            name='hr',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_hr_module_subscription', to='authorization.HrModule'),
        ),
        migrations.AddField(
            model_name='usersubscriptions',
            name='training',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_training_module_subscription', to='authorization.TrainingModule'),
        ),
        migrations.AddField(
            model_name='usersubscriptions',
            name='user_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_group_subscriptions', to='authorization.UserGroup'),
        ),
    ]
