# Generated by Django 2.1.3 on 2019-03-19 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_auto_20190307_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscriptions',
            name='connect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_connect_module_subscription', to='authorization.ConnectModule'),
        ),
        migrations.AlterField(
            model_name='usersubscriptions',
            name='engage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_engage_module_subscription', to='authorization.EngageModule'),
        ),
        migrations.AlterField(
            model_name='usersubscriptions',
            name='hr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_hr_module_subscription', to='authorization.HrModule'),
        ),
        migrations.AlterField(
            model_name='usersubscriptions',
            name='training',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_training_module_subscription', to='authorization.TrainingModule'),
        ),
    ]
