# Generated by Django 2.1.3 on 2019-03-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_auto_20190319_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectmodule',
            name='company_uuid',
            field=models.CharField(blank=True, help_text='UUID from company table', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='engagemodule',
            name='company_uuid',
            field=models.CharField(blank=True, help_text='UUID from company table', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='hrmodule',
            name='company_uuid',
            field=models.CharField(blank=True, help_text='UUID from company table', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='trainingmodule',
            name='company_uuid',
            field=models.CharField(blank=True, help_text='UUID from company table', max_length=150, null=True),
        ),
    ]
