# Generated by Django 2.1.3 on 2019-03-27 04:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authorization', '0004_auto_20190324_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysubscriptions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='companysubscriptions',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companysubscriptions',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active',
                                   max_length=8),
        ),
        migrations.AddField(
            model_name='companysubscriptions',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active',
                                   max_length=8),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubscriptions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubscriptions',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersubscriptions',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active',
                                   max_length=8),
        ),
        migrations.AddField(
            model_name='usersubscriptions',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
